-- Coin SQL Dummy Data
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('btc', 'Bitcoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('eth', 'Ethereum', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usdt', 'Tether', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('xrp', 'XRP', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bnb', 'BNB', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('sol', 'Solana', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usdc', 'USDC', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('doge', 'Dogecoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ada', 'Cardano', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('trx', 'TRON', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('steth', 'Lido Staked Ether', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('wbtc', 'Wrapped Bitcoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('sui', 'Sui', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('link', 'Chainlink', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('avax', 'Avalanche', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('wsteth', 'Wrapped stETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('xlm', 'Stellar', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('shib', 'Shiba Inu', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('hbar', 'Hedera', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('hype', 'Hyperliquid', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ton', 'Toncoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bch', 'Bitcoin Cash', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('leo', 'LEO Token', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usds', 'USDS', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ltc', 'Litecoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('dot', 'Polkadot', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('weth', 'WETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('xmr', 'Monero', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('weeth', 'Wrapped eETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bgb', 'Bitget Token', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('pepe', 'Pepe', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('pi', 'Pi Network', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bsc-usd', 'Binance Bridged USDT (BNB Smart Chain)', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('cbbtc', 'Coinbase Wrapped BTC', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usde', 'Ethena USDe', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('wbt', 'WhiteBIT Coin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('tao', 'Bittensor', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('uni', 'Uniswap', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('near', 'NEAR Protocol', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('apt', 'Aptos', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('dai', 'Dai', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('okb', 'OKB', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('aave', 'Aave', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ondo', 'Ondo', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('susds', 'sUSDS', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('etc', 'Ethereum Classic', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('icp', 'Internet Computer', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('cro', 'Cronos', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('buidl', 'BlackRock USD Institutional Digital Liquidity Fund', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('trump', 'Official Trump', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('kas', 'Kaspa', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('gt', 'Gate', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('tkx', 'Tokenize Xchange', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('vet', 'VeChain', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('render', 'Render', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('mnt', 'Mantle', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('pol', 'POL (ex-MATIC)', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('atom', 'Cosmos Hub', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('fet', 'Artificial Superintelligence Alliance', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ena', 'Ethena', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usd1', 'USD1', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('lbtc', 'Lombard Staked BTC', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('algo', 'Algorand', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('fil', 'Filecoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('susde', 'Ethena Staked USDe', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('tia', 'Celestia', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('s', 'Sonic (prev. FTM)', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ftn', 'Fasttoken', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('arb', 'Arbitrum', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bonk', 'Bonk', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('wld', 'Worldcoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('jlp', 'Jupiter Perpetuals Liquidity Provider Token', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('jup', 'Jupiter', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('stx', 'Stacks', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('fdusd', 'First Digital USD', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('eos', 'EOS', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('mkr', 'Maker', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('weth', 'Binance-Peg WETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('kcs', 'KuCoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('bnsol', 'Binance Staked SOL', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('qnt', 'Quant', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('fartcoin', 'Fartcoin', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('rseth', 'Kelp DAO Restaked ETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('flr', 'Flare', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('sei', 'Sei', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('nexo', 'NEXO', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('op', 'Optimism', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('virtual', 'Virtuals Protocol', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('imx', 'Immutable', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('xdc', 'XDC Network', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('ip', 'Story', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('inj', 'Injective', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('solvbtc', 'Solv Protocol BTC', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('grt', 'The Graph', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('reth', 'Rocket Pool ETH', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('usdt0', 'USDT0', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('crv', 'Curve DAO', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('floki', 'FLOKI', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('wbnb', 'Wrapped BNB', NOW(), NOW());
INSERT INTO coin (symbol, name, created_at, updated_at) VALUES ('theta', 'Theta Network', NOW(), NOW());
